trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    arguments: '--configuration $(buildConfiguration)'
    projects: 'src/SmartThings.NETCoreWebHookSDK/SmartThings.NETCoreWebHookSDK.csproj'

- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    arguments: '--norestore --configuration $(buildConfiguration)'
    projects: 'src/SmartThings.NETCoreWebHookSDK/SmartThings.NETCoreWebHookSDK.Tests.csproj'

- task: DotNetCoreCLI@2
  inputs:
    command: 'pack'
    packagesToPack: 'src/SmartThings.NETCoreWebHookSDK/SmartThings.NETCoreWebHookSDK.csproj'
    nobuild: true
    includesymbols: true
    versioningScheme: 'off'


