# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: DotNetCoreCLI@2
  displayName: 'Build'
  inputs:
    command: 'build'
    arguments: '--configuration Release'
    projects: 'samples/SmartThings.NETCoreWebHookSDK.Samples.sln'
- task: DotNetCoreCLI@2
  displayName: 'Test'
  inputs:
    command: 'test'
    nobuild: true
    projects: 'samples/SmartThings.NETCoreWebHookSDK.Samples.sln'
- task: DotNetCoreCLI@2
  displayName: 'Pack'
  inputs:
    command: 'pack'
    nobuild: true
    arguments: '--configuration Release'
        packagesToPack: 'src/SmartThings.NETCoreWebHookSDK/SmartThings.NETCoreWebHookSDK.csproj'
