name: .NET 5 Samples

on:    
  workflow_dispatch:
  push:
    branches: [ main ]    
    paths:
    - 'samples/**'
    - '.github/workflows/dotnet-5-samples.yml'
    
  pull_request:
    branches: [ main ]
    paths:
    - 'samples/**'
    - '.github/workflows/dotnet-5-samples.yml'
    
jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest  
    
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET 5
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Install dependencies
      run: dotnet restore samples/SmartThings.NETCoreWebHookSDK.Samples.sln
      
    - name: Build
      run: dotnet build samples/SmartThings.NETCoreWebHookSDK.Samples.sln
        --configuration Debug
        --no-restore
