name: .NET 5 CI

on:
  pull_request:
    branches: [ master ]
    paths:
    - 'src/**'
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET 5
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Install dependencies
      run: dotnet restore src/SmartThings.NETCoreWebHookSDK.sln
    - name: Build
      run: dotnet build src/SmartThings.NETCoreWebHookSDK.sln
        --configuration Release
        --no-restore
    - name: Test
      run: dotnet test src/SmartThings.NETCoreWebHookSDK.sln
        --no-restore

