name: .NET Core CD

on:
  push:
    branches: [ master ]
    paths:
    - 'src/**'
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore src/SmartThings.NETCoreWebHookSDK.sln
    - name: Build
      run: dotnet build src/SmartThings.NETCoreWebHookSDK.sln
        --configuration Release
        --no-restore
    - name: Test
      run: dotnet test src/SmartThings.NETCoreWebHookSDK.sln
        --no-restore
    - name: Publish Nuget Package to Nuget
      run: dotnet nuget push src/SmartThings.NETCoreWebHookSDK/bin/Release/*.nupkg
        --api-key ${{ secrets.NUGET_DEPLOY_KEY }}
        --source https://api.nuget.org/v3/index.json
    - name: Publish Nuget Package to GitHub
      uses: tanaka-takayoshi/nuget-publish-to-github-packages-action@v2.1
      with:
        nupkg-path: src/SmartThings.NETCoreWebHookSDK/bin/Release/*.nupkg
        repo-owner: ianisms
        gh-user: ianisms
        token: ${{ secrets.PAT }}
        skip-duplicate: true

