name: .NET 5 CI / CD

on:    
  workflow_dispatch:
  push:
    branches: [ main ]
    
  pull_request:
    branches: [ main ]
    paths:
    - 'src/**'
    - '.github/workflows/dotnet-5-cicd.yml'
    
jobs:
  build:
    name: Build, Test, Analyze, and Deploy
    runs-on: ubuntu-latest  
    
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language: [ 'csharp' ]
        # CodeQL supports [ 'cpp', 'csharp', 'go', 'java', 'javascript', 'python' ]
        # Learn more:
        # https://docs.github.com/en/free-pro-team@latest/github/finding-security-vulnerabilities-and-errors-in-your-code/configuring-code-scanning#changing-the-languages-that-are-analyzed
    
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET 5
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Install dependencies
      run: dotnet restore src/SmartThings.NETCoreWebHookSDK.sln
      
    - name: Build
      run: dotnet build src/SmartThings.NETCoreWebHookSDK.sln
        --configuration Release
        --no-restore
        
    - name: Test
      run: dotnet test src/SmartThings.NETCoreWebHookSDK.sln
        --no-restore
      
    # Initializes the CodeQL tools for scanning.
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v1
      with:
        languages: ${{ matrix.language }}
        # If you wish to specify custom queries, you can do so here or in a config file.
        # By default, queries listed here will override any specified in a config file.
        # Prefix the list here with "+" to use these queries and those in the config file.
        # queries: ./path/to/local/query, your-org/your-repo/queries@main        

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v1
      
    - name: Publish Nuget Package to Nuget
      run: dotnet nuget push src/SmartThings.NETCoreWebHookSDK/bin/Release/*.nupkg
        --api-key ${{ secrets.NUGET_DEPLOY_KEY }}
        --source https://api.nuget.org/v3/index.json
        --skip-duplicate
