name: .NET 5 CI / CD

on:    
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
    - 'src/**'
    - '.github/workflows/dotnet-5-cicd.yml'
    
  pull_request:
    branches: [ main ]
    paths:
    - 'src/**'
    - '.github/workflows/dotnet-5-cicd.yml'
    
jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest  
    
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET 5
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Install dependencies
      run: dotnet restore src/SmartThings.NETCoreWebHookSDK.sln
      
    - name: Build
      run: dotnet build src/SmartThings.NETCoreWebHookSDK.sln
        --configuration Release
        --no-restore
        
    - name: Test
      run: dotnet test src/SmartThings.NETCoreWebHookSDK.sln
        --no-restore
        
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    needs: build
    
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language: [ 'csharp' ]
        # CodeQL supports [ 'cpp', 'csharp', 'go', 'java', 'javascript', 'python' ]
        # Learn more:
        # https://docs.github.com/en/free-pro-team@latest/github/finding-security-vulnerabilities-and-errors-in-your-code/configuring-code-scanning#changing-the-languages-that-are-analyzed

    steps: 
    - name: Checkout Code
      uses: actions/checkout@v2
      
    # Initializes the CodeQL tools for scanning.
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v1
      with:
        languages: ${{ matrix.language }}
        # If you wish to specify custom queries, you can do so here or in a config file.
        # By default, queries listed here will override any specified in a config file.
        # Prefix the list here with "+" to use these queries and those in the config file.
        # queries: ./path/to/local/query, your-org/your-repo/queries@main        
    
    - name: Checkout Code
      uses: actions/checkout@v2
      
    - name: Setup .NET 5
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Install dependencies
      run: dotnet restore src/SmartThings.NETCoreWebHookSDK.sln
      
    - name: Build
      run: dotnet build src/SmartThings.NETCoreWebHookSDK.sln
        --configuration Release
        --no-restore
      
    # Autobuild attempts to build any compiled languages  (C/C++, C#, or Java).
    # If this step fails, then you should remove it and run the build manually (see below)
    #- name: Autobuild
    #  uses: github/codeql-action/autobuild@v1
        
    # ℹ️ Command-line programs to run using the OS shell.
    # 📚 https://git.io/JvXDl

    # ✏️ If the Autobuild fails above, remove it and uncomment the following three lines
    #    and modify them (or add more) to build your code if your project
    #    uses a compiled language

    #- run: |
    #   make bootstrap
    #   make release

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v1
        
  Deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [build, analyze]

    steps: 
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Setup .NET 5
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Install dependencies
      run: dotnet restore src/SmartThings.NETCoreWebHookSDK.sln
      
    - name: Build
      run: dotnet build src/SmartThings.NETCoreWebHookSDK.sln
        --configuration Release
        --no-restore
      
    - name: Publish Nuget Package to Nuget
      run: dotnet nuget push src/SmartThings.NETCoreWebHookSDK/bin/Release/*.nupkg
        --api-key ${{ secrets.NUGET_DEPLOY_KEY }}
        --source https://api.nuget.org/v3/index.json
        --skip-duplicate
